### ISSUE TITLE
Availability on the French AppStore?

### ISSUE THREAD

**Issue by dickolsson** [padloc/padloc#105]
Would it be possible to submit Padlock to the French Apple AppStore? Asking for a friend :)

**Comment by MaKleSoft** [comment]
Unfortunately, due to the way that encryption is implemented in Padlock, we'd need to acquire a French encryption declaration approval from the ANSSI, [which is a notoriously difficult and lengthy process](https://cryptomator.org/blog/2016/06/16/indepth-french-app-store_en.html). The good news is that we're planning to make some changes to the code base that will likely remove that requirement (Specifically, we'll exclusively be using the crypto implementations shipped with iOS). Expect Padlock to be available in the French App Store starting with version 2.1.

**Comment by DrGeek** [comment]
Any news :D ?

**Comment by MaKleSoft** [comment]
> Expect Padlock to be available in the French App Store starting with version 2.1.

Boy, did we not deliver on that promise 😬Sorry about that. We never did end up making the changes that I alluded to in my last comment. The good news is that starting with v3, `[SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) will be used in place of `sjcl` for all encryption algorithms, which hopefully counts as "accessing or using the encryption in iOS", removing the ANSSI approval requirement. I can't really tell for sure yet, though. We'll just have to reevaluate once we're ready to submit v3 to the app store. Sorry for the long wait!

**Comment by BrunoBernardino** [comment]
Padloc has been available in the French App Store for a while now: https://apps.apple.com/fr/app/padloc/id1478877043
