### ISSUE TITLE
OSX desktop app should lock when device goes into sleep mode.

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#211]
Should use [power-monitor](https://electronjs.org/docs/api/power-monitor) electron module to listen for `suspend` event and lock the app when the device goes to sleep.

**Comment by combinatorist** [comment]
This may warrant a separate ticket, but may also be related. Another user of padloc (v3) on OSX told me they ocassionally find it open hours after their 5 minute limit should have expired. OTOH, they know their limit is set because it usually works.

Also, maybe separate, but related, they reported that when they minimize padloc and reopen later, it still has an image of its last open state which stays visible for about 3 seconds before it actually locks. This may be some caching you can't control on OSX or in electron, but it's obviously not ideal for a pw manager.

**Comment by MaKleSoft** [comment]
@combinatorist Thanks for bringing this up! I think using the suspend event should take care of that problem as well.
