### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by beli3ver** [padloc/padloc#215]
I only want to know if this project is still active?
The last update was in June 2018.
Thanks

**Comment by MaKleSoft** [comment]
Yes, more active than ever in fact! We're working in a major new release and most of the work is happening in the v3 branch right now which is why the project may be looking a little stale. But we'll have some very existing new stuff to share very soon, so stay tuned! 😉

**Comment by mandusm** [comment]
I've been a huge fan of Padlock for the last two years. 
Primarily, I have loved the idea that I can host my own server and not have to sync to someone else's infrastructure. I also love the simple interface. Lately though, some of the newer IOS integrations products like DashLane and LastPass has, have made me consider the move... 

Can you maybe comment on some of the newer features you are busy building?
For example, would the iOS password integration be a feature? Also, would you support FaceId?

**Comment by MaKleSoft** [comment]
@mandusm Thanks for the feedback! I definitely see where you're coming from. Historically, Padlock has always been trying to set itself apart with a **lack** of features, focusing on simplicity and robustness rather than unnecessary "gimmicks". Lately however we've realized that in order to stay relevant in the landscape of modern password managers we'll have to shed that philosophy to some degree.

v3 is **a lot** more ambitious than the previous versions in many ways, and we'll be announcing a number of features that users have been asking for for a while. And although this comes with a significant increase in complexity, I think we've found a good balance between a much more complete and powerful feature set and the simple and intuitive user experience that people have come to love in previous versions of Padlock.

Just a few examples of the new features that we'll be introducing in v3:

- Shared Vaults
- Encrypted file storage
- TOTP support
- A PWA interface (loadable through any modern browser)
- Better browser and platform integration

In addition to all this, spinning up your own Padlock instance is going to be easier than ever and we'll be introducing more administrative features like user whitelisting as well. 

As for iOS integration specifically - I'm an iOS user as well and although I'm somewhat weary of the security implications, I've been longing for the added convenience of better platform integration as well and we've come to the conclusion that it may outweigh the risks after all (FaceID/TouchID for example will hopefully encourage users to choose stronger passwords).

So to wrap up: Yes, FaceID/TouchID will come to iOS and we'll also be working on better browser and platform integration in general although some of this will probably be introduced incrementally after the launch of v3.0.

I know we've been teasing v3 for a while now and I definitely appreciate all of your patience!  But it looks like we'll have some official announcements very soon... stay tuned! 😉

**Comment by mandusm** [comment]
Fantastic. 
This sounds very promising! I've always loved the simplicity of Padlock, but like you mentioned, some of the modern conveniences is becoming more important for me. I'm not so concerned about browser integration, but FaceID. iOS password integration and Shared Vaults is the big ones for me. 

I cloned and checked out out the v3 branch a few days ago and gave a quick swing at building it and testing it out. Unfortunately the build failed and I didn't really spend much time trying to debug it. 

I'd love to be an alpha tester and help you out where I can. I'd love to help add support for things like Amazon SES integration etc.

**Comment by MaKleSoft** [comment]
Okay, so the v3 branch is merged and we just announced the upcoming release of Padloc 3 https://padloc.app/news/announcing-v3/
If that doesn't answer the question of inactivity I don't know what will 😄Accourdingly I'm closing this issue.

All feedback and help is welcome of course! In fact, we actively looking for beta testers for Padloc 3 right now so if you're interested shoot me an email at martin@padloc.app!

@mandusm If you're still experiencing the build error, please create a new issue with the details and we'll look into it. Thanks!
