### ISSUE TITLE
Client to Server Upload Sync

### ISSUE THREAD

**Issue by mandusm** [padloc/padloc#232]
In Padloc `v2` if my self-hosted sync-server went down for whatever reason, I could simply relaunch it and have any of my existing clients `login` to the server again.

At this point, the client would then upload all it's items up to the server and it would sync with all other devices I would log in with again.

`v3` acts differently. If the server goes down and loses data, it remote-wipes the client device on `login`.

I believe this is an almost similar request to #70

**Comment by MaKleSoft** [comment]
> In Padloc v2 if my self-hosted sync-server went down for whatever reason, I could simply relaunch it and have any of my existing clients login to the server again.
> 
> At this point, the client would then upload all it's items up to the server and it would sync with all other devices I would log in with again.

I'm afraid this pattern simply won't work with the new architecture. Your data is still stored locally though so there is a different (and more transparent, albeit slightly more elaborate) way to recover your data in case your server goes down:

0. (Don't restart the server yet)
1. Unlock the app (It'll show you're offline, but you should still be able to unlock)
2. Export your data
3. Logout
4. Restart the server
5. Create a new account
6. Reimport your data

In general, it's a good idea to keep regular backups of your data in the form of local, encrypted exports so you're not dependent on the server *or* the apps internal storage mechanism.

 > If the server goes down and loses data, it remote-wipes the client device on login.

This is the main problem here. Basically if the the server rejects the clients session (because it can't find the corresponding session id in the database), the client assumes that the session has been revoked and thus wipes the locally stored data. Note that this won't happen if the server is down, only if you restart it with an empty database. So I guess just don't restart your server until you've recovered the data? (And keep local backups, like mentioned earlier)

**Comment by mandusm** [comment]
Cool. Makes sense...
Do we want to consider then adding the ability to export backups on the mobile clients then? Right now that doesn't seem to be working? 

It would be nice to be able to export and save backups directly to services like Dropbox/Google Drive

**Comment by MaKleSoft** [comment]
Actually, exporting should be supported on mobile clients as well. Just tested it on iOS and it is in fact broken. I'll create an issue for that. Saving backups files to your Dropbox or any other kind of cloud storage should be trivial and wouldn't require any explicit integration. In fact, the save dialog on iOS offers Dropbox and iCloud as standard options if I recall correctly.

So I guess we can close this now?

**Comment by mandusm** [comment]
Yup. Closing it.
