### ISSUE TITLE
Confusing subscription system

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#239]
My understanding is that there is one subscription per team or organization, which makes sense. 

However, even when we are part of a paid subscription in a team or organization:
- we continue to be prompted to "get premium"
- our personal vault is still limited to 50 items. 

Shouldn't we get access to unlimited personal items when part of a paid plan? As the manager of an organization's plan, I want my team members to not have to worry about any additional plan/subscription/payment and simply follow the invite and easily start using.

**Comment by MaKleSoft** [comment]
I understand what you're saying and we're thinking about ways to implement this (currently we don't offer this mainly for technical reasons). Since this is not a technical question though, this really isn't the right place to discuss this so I'm closing this issue. If you want to discuss this further, we can do that via email :)
