### ISSUE TITLE
Need for a quick way to access different categories of items

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#241]
At the moment, there is no way to filter items such as "credit cards", "bank accounts", etc.

**Comment by MaKleSoft** [comment]
Well, the thing is that Padloc doesn't have "categories" in the sense you're referring to. Vault items are, by design, completely free-form, meaning that they can have an arbitrary collection of fields. Padloc lets you select from a list of "Templates", which basically are just a predefined configuration 
of fields (which can be changed, deleted or reordered at any time). Currently, the app doesn't remember which template you chose initially, so we can't filter by that criterium.

I know that other password managers group their items into things like "Logins", "Credit Cards" etc. but I honestly don't see the value in that. If for example I want to find my companies visa card I search for "Visa" in the "Finance" vault of the corresponding organization. I don't see how having a way to list all credit cards would make this task easier?

If you want to organize items into "categories", tags are a much more flexible and powerful way to do that. If you absolutely want a way to list all your credit cards, simply add a tag "credit cards" to all of them. Or you could group them together with your bank accounts and call the tag "finance". Does that make sense? Or am I missing something?

**Comment by mandusm** [comment]
I'm totally in support of the way Padloc does it right now. In fact, it is one of the primary things I love about it above any other password managers. The free form item design is so practical and allows me to store whatever information I want per item. I frequently have `Email`, `Username`, `RSA Private Key`, `etc` stored in a single item.

Tags have worked very well for me in grouping items together. Also, in Padloc 3, I have been adding to this by separating into vaults.

**Comment by Raph33** [comment]
@MaKleSoft it makes total sense! I like this way much better in fact--more flexility and freedom to organize as we wish. I was just stuck in the old password manager way so I didn't get that immediately :)
