### ISSUE TITLE
[Feedback Wanted] Add instructions for hosting/running your own Padloc suite

### ISSUE THREAD

**Issue by ghost** [padloc/padloc#254]
I know you've confirmed with me off-list that the newer Padloc will have hosting instructions and instructions on how to build the mobile apps for using these custom instances (since the newer apps won't support custom instance for syncing anymore) added to their repositories.

I'm opening this bug to track the efforts for these tasks, since as much as I love the new service(s) (and am I beta user myself) I won't use a centralized, managed service to sync my passwords. 

Padlock, in the past, has been a phenomenal tool for managing my passwords and secrets efficiently and I would love for Padloc to carry on this legacy.

PS: Obviously, I'd rather love to have the official apps support custom servers, but right now there isn't any other choice I'm afraid

**Comment by MaKleSoft** [comment]
Thanks for creating the ticket! We do want to significantly improve the documentation in this area, unfortunately there's been tons of other stuff to do so this hasn't received the attention it probably deserves. For what it's worth, all the tooling is already there and setting up your instance is already incredibly easy, all that's missing is a simple step-by-step guide. Give @mheiber-tier a thumbs-up if you want us to raise this issue in priority!

**Comment by mheiber-tier** [comment]
@MaKleSoft That's for the quick answer, and thank you to everyone who has given their thumbs up already!

Honestly, I'd be more interested in building my own apps, because that's the missing link for me. Getting the server running is probably a few sessions of trial and error (and reading code), but getting the apps set up (and onto my phone(s)) is another level entirely.

**Comment by MaKleSoft** [comment]
> PS: Obviously, I'd rather love to have the official apps support custom servers, but right now there isn't any other choice I'm afraid

As I explained elsewhere, the reason why we're not supporting this in the new version is due to security concerns (we've tightened the content security policy to only allow requests to the official server). I do understand that building your own version may be too much work for most people (especially for iOS where you need a paid developer account) and we're thinking  about releasing a semi-official "community edition" of all client builds that can be hooked up to a custom backend. Is that something that would work for you?

**Comment by mheiber-tier** [comment]
@MaKleSoft That would be fantastic, yes, since that'll make it heaps easier on folks to run their own stacks instead of having to basically forego all the advantages of the cross-platform aspects of the app. Thank you!

**Comment by luxaritas** [comment]
@MaKleSoft 
> As I explained elsewhere, the reason why we're not supporting this in the new version is due to security concerns (we've tightened the content security policy to only allow requests to the official server)
I've looked through the issues and don't see such an explanation, barring #16 where the end result was "relaxing the CSP isn't an issue". Have you explained somewhere what the security concern being addressed is?

**Comment by MaKleSoft** [comment]
@luxaritas This is really less about any specific attack vectors and more about general caution. Hardcoding the server url at build time allows us to use a tighter CSP which mitigates any sort of attack trying to change the server url at runtime. More importantly though, allowing the user to provide their own url opens the app up to a whole class of new attack vectors, from social engineering attacks (like someone sending out emails to Padloc users asking to change the server url, because reasons) to server misconfiguration, domain hijacking etc etc. The official app is used mainly by "normal" users, i.e. the percentage of users who want to configure their own server is fairly small, so to loosen the security of the app (by whatever small margin) to accommodate for this group of users is a tradeoff we're not ready to make a this point, at least not for the official app. As I said, releasing a "community edition" semiofficial build that comes with warnings about all the possible caveats of providing your own backend may be a good compromise here.

**Comment by larshg** [comment]
Hi @MaKleSoft 

I tried run the server on a ubuntu server, but when I hit the webpage, it just show the login/sign up view, but also shows offline in the top.

Its local hosted server running in virtualbox with network bridge, with the ip as seen in the log.

How do it get it "online" :) ?

![image](https://user-images.githubusercontent.com/1165340/75541879-f0947000-5a1e-11ea-9d80-5312b4e16024.png)

**Comment by MaKleSoft** [comment]
@larshg Can you open dev tools in the browser and check the network log and console output please?

**Comment by larshg** [comment]
Hmm, it seems to connect to 0.0.0.0:3000 - I have set the two enviroment values.
Where do I need to change the IP?

**Comment by MaKleSoft** [comment]
Can you try either the exporting the env variables or passing them directly in the command? I.e.:

```sh
PL_SERVER_URL=... npm start
```

**Comment by swrap** [comment]
# Issue
Ran into a problem with the [docker-compose](https://github.com/padloc/padloc/blob/master/docker-compose.yml) file is that it uses the Dockerfile shares the same environmental variable names as the webpack.

# Example

## Assumption
Lets assume we have the following environmental variable set:
```
PL_SERVER_URL=8000
```
## Explanation
In the [packages/pwa/webpack.config.js](https://github.com/padloc/padloc/blob/master/packages/pwa/webpack.config.js) the following is used for the server url
```
...
const serverUrl = process.env.PL_SERVER_URL || `http://0.0.0.0:${process.env.PL_SERVER_PORT || 3000}`;
...
```
This causes the `PL_SERVER_PORT` to be hard-coded during the `docker build` process for each of the pieces of the padloc app.

Then in the (docker-compose)[https://github.com/padloc/padloc/blob/master/docker-compose.yml] file there is a mapping for the ports:
```
...
        ports:
            - $PL_SERVER_PORT:3000
...
```
The port `8000` gets mapped to port `3000`, however during the `docker build` we have port `8000` hard coded into the source code. This means that docker maps `8000->3000`, but the server is running in the docker container on port `8000`. Therefore it will not work.

# Remedy

## Short Term
- During your docker build make sure no environmental variables are set.
  - Pros
    - Easy to do
 - Cons
    - If you forget than you will a lot of problems
    - Cumbersome for automatic builds if you want to set it a custom port just for the docker container
## Long Term
1. Change the environmental variable for the docker build.
 - Pros
    - Keeps local npm run separate from docker environmental variables
2. Change the `docker-compose` file to map `PL_SERVER_PORT:PL_SERVER_PORT`
 - Pros
    - Easy to understand and will map accordingly for `docker build`
 - Cons
    - Must keep the environmental variable consistent
3. Others... I can't think of right now. Open to suggestions!

**Comment by MaKleSoft** [comment]
@swrap Good catch! Would you mind creating a separate issue for this though?

**Comment by swrap** [comment]
> @swrap Good catch! Would you mind creating a separate issue for this though?

Sure thing. Put it here for anyone who is running into some troubles starting it up at home.

**Comment by pihentagy** [comment]
Hi!

Can I expect a docker compose based install guide in the forseeable future?

thanks

**Comment by MaKleSoft** [comment]
@pihentagy Yes! Working on it right now, actually. Hope to finish it over the weekend 😊

**Comment by MaKleSoft** [comment]
Ok so here it is, finally... https://padloc.app/help/guides/self-host/

Sorry for the long wait! Note that this is only a first version and we'll be updating it and adding things as we further refine the setup process and cover more use cases.

Please do let us know if you have any feedback or suggestions! Anything that isn't explained clearly enough? Anything you'd like us to add or cover in more detail? I'll keep this issue open for now for the purpose of gathering feedback.

**Comment by detobel36** [comment]
What are the step to have self-host on android application ?

I supposed I must to local compile app ?

**Comment by swrap** [comment]
> What are steps to have self-host on android application ?
> 
> I supposed I must to local compile app ?

Yes, I am pretty sure you do because of the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

**Comment by detobel36** [comment]
Yes okay but how to build it ? :stuck_out_tongue_closed_eyes:

**Comment by MaKleSoft** [comment]
@detobel36 The "official" desktop and mobile apps currently don't support using a self-hosted server. [PWA support on Android](https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&oco=1) is pretty good though. Basically the only feature you don't get from a PWA currently is biometric authentication (using the fingerprint sensor or facial recognition to unlock).

We are planning to add a guide about how to build Padloc for Android and other platforms but this may be some way off as we're currently evaluating [a completely new deployment system](https://github.com/padloc/padloc/tree/master/packages/tauri) for mobile and desktop. But for now using the PWA is pretty good alternative I think.

**Comment by Carlosgrr** [comment]
I just followed the instructions from https://padloc.app/help/guides/self-host/.
The login page displays correctly using the correct certificate, but on the top of the page there is a red label warning that the server is offline and when I try to create a username and password it doesn't respond. Am I missing any step not documented yet?

**Comment by adyanth** [comment]
Is there any progress on this front? Will we be able to use the android app pointed to custom servers? Looks damn good if it works!

**Comment by MaKleSoft** [comment]
@adyanth I don't have an update on using custom servers in the native Android app, but I can tell you that we're working on bringing biometric unlock to the PWA as well! That would basically close the gap to the native app in terms of features/usability so at that point I don't actually see the value of installing the native app vs using the PWA, at least in regards of UX. Is there any other reason why you'd prefer installing a native App vs using a self-hosted PWA?

**Comment by adyanth** [comment]
@MaKleSoft so, everything will work the same on PWA? The autofills and the like? I haven't given this a try because I was expecting it work cross platform without any issues. Biometric addition will be amazing, and if the autofills work well across browsers and apps on android, I'm good! 

I'll try this out this week and see if I observe any shortcomings. Thanks!

**Comment by c4lliope** [comment]
Hello all; I'm sorry to be the one to make this recommendation, though I can claim no patience for a program which disregards the needs of their users as though they're meaningless. Anyone seeing this kind of issue (basically, all besides the paying customers) should begin using https://www.passbolt.com/ - their apps and browser addons ask for the custom URL on the first screen, and since July 2022 I've been using them with no issue - simly make sure you keep a copy of the GPG key you're assigned on signup so you can log in from other machines.

I had high hopes for Padloc upon seeing such slick design and clear security audits displayed in their branding. I had even been able to deploy the program on my homelab's Dokku alongside all my homemade code. After a couple days of hacking on the deployment I'd been sure I had a good solution. Then as soon as I reached for the browser extension and android apps I realized I had a serious problem.

11 months ago, @MaKleSoft had said:

> Hi there! For security reasons, we do not currently support pointing the official apps to a custom server. However, are working on improving the tooling and documentation around building your own custom version of all apps and extensions! Additionally, we are considering releasing a "community edition" of all apps, which can be configured to be used with a custom server.

The "security" reason here is a red herring - custom domains are likely more secure than a single high-profile corporate domain handling all accounts. Padloc's programmers are saying, "you can run this yourself - if you can manage as large a presence on the app and browser stores as we do." This precludes any usage by the open-source coders who would likely help to make upgrades to the codebase after using it for personal or company use.

Padloc is disregarding user needs because they're picky regarding who their users are.
I do hope they make good on their promise of a "community edition" and once this happens I may rescind this.
For now, I'll be going back to https://www.passbolt.com/ and I recommend the same for many of you.

**Comment by mike-engel** [comment]
Bitwarden (what I'm currently using) also has the same feature to [choose a server on login](https://bitwarden.com/help/change-client-environment/). It would be great to have that here, too
