### ISSUE TITLE
Browser Extension Feedback And Wishlist

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#265]
Good news! We've started working on the browser extension and will have something to show very soon! In the meantime, we'd love to get some feedback about what features you'd like to see, how the optimal auto-fill flow would look like for you etc. So we'd really appreciate if you could take a moment and answer the following questions (just reply to this issue):

1. Have you used other password manager browser extensions before? If yes, ...
    a) which?
    b) How reliable was the auto-fill in general?
    c) Where there any instances where the auto-fill did **not** work as expected / intended?
    d) Anything specific you really liked?
    e) Anything specific that bothered you?
    f) Did you encounter any performance issues?
2. What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10)
3. Do you have any specific security-related concerns?
4. Rate the following aspects in terms of priority (1 - 10)
    a) convenience
    b) security
    c) performance
5. Anything else you'd like to add?

**Comment by mzch** [comment]
1)
  a) 1password, Dashlane and Bitwarden
  b) almost complete except Dashlane
  c) https://card.surugabank.co.jp/Top.do - 1password works but bitwarden doesn't work
  d) Auto-save login credentials
  e) Dashlane shows a popup dialog to save login info many times.
  f) No.
2)
 a) auto-save - 10
 b) add/edit/delete password from extensions - 8
 c) search credentials in extensions - 8
 d) of course, ability to deal with my own instance - 10
3) Password-less authentication
4)
 a) 8
 b) 10
 c) 5
5) None.

**Comment by jimvonmoon** [comment]
1. No extensions, only browser built-in managers
   a) I used mainly the default Firefox password manager.
   b) For me FF's auto-fill it is like 99.9% accurate. Certainly good enough.
   c) I think I encountered only 1 or 2 pages which didn't play nice with FF's auto-fill (usually some obscure corporate intranet stuff).
   d) It's readily available after FF installation, lightweight, supports multiple accounts per site, and comes with a password explorer which lets you access and edit all saved credentials.
   e) From what I've read its encryption is pretty weak (https://bit.ly/383klfm).
   f) No.
2. What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10)
   - [10] Auto-sync with cloud (also local cloud!)
   - [10] Support for Firefox (especially on Windows, Android and Linux)
   - [9]  Multiple accounts per site
   - [9]  Credentials explorer/editor (it could be the regular Padloc app, but aware of certain entries being website login credentials)
   - [1]  Hardware authentication token support (U2F, FIDO2)
3. Do you have any specific security-related concerns?
   - Strong encryption is a must.
   - The amount of time unencrypted master password and login credentials are kept in memory should be reduced to minimum. I wouldn't want my credentials being sent anywhere in a core dump included in browser's crash report.
   - Dialog for entering master password should have some distinct look. E.g. default FF's dialog is so simple it's hard to tell if it's genuine or comes from some sort of phishing malware.
4. Rate the following aspects in terms of priority (1 - 10)
   a) [7]  convenience
   b) [10] security
   c) [5]  performance (I don't expect a password manager to slow down a browser during operation, but it would be pretty bad if it caused significant slowdown during browser launch)
5. Not really, thanks for looking into browser extensions! :-)

**Comment by loggerhead-turtle** [comment]
Have you used other password manager browser extensions before? If yes, ...
a) which?--last pass and keeper.
b) How reliable was the auto-fill in general?--lastpass was high quality, keeper high quality when logged in
c) Where there any instances where the auto-fill did not work as expected / intended?--when I wasn't logged in, or if the app URL and website URL don't match
d) Anything specific you really liked?--Keeper helps me change passwords.  When I click on the password update in a website, Keeper will walk me through the steps to change the password and recommending a new password along the way.
e) Anything specific that bothered you?--Keeper logs out too frequently.  
f) Did you encounter any performance issues?--no
What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10)--login for different users, option to turn on or off auto-fill and auto-fill with login, specify logout timeframe, Support Titan security key (more of a global request)
Do you have any specific security-related concerns?
Rate the following aspects in terms of priority (1 - 10)
a) convenience 1
b) security
c) performance
Anything else you'd like to add?--Provide autofill from the website and app and I'll drop Keeper and become a paid user.

**Comment by RunAwayyyy** [comment]
1. Have you used other password manager browser extensions before? 
  - *No*
2. What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10)
  - [10] Firefox support on Linux
  - [8] Auto-sync
  - [8} Auto-fill
  - [6] If I register an account somewhere, make it easy to create an entry and generate some password, by right clicking on a field or something
  - [3] A way to manually specify which fields of an entry belong to which part of a form (and keep that information, so I don't always have to do it)
  - [5] Password less authentication
3. Do you have any specific security-related concerns?
  - Strong encryption
  - Code run in my tabs, should not be able to interact with Padloc (I have zero insights if anything like this is possible, or problematic or anything. It just popped up in my mind)
4. Rate the following aspects in terms of priority (1 - 10)
    a) [8] convenience
    b) [10] security
    c) [5] performance
5. Anything else you'd like to add?
Not right now, really looking forward to it!

**Comment by ContentPersonality2** [comment]
**Have you used other password manager browser extensions before?:**
Yes, I'm currently using Bitwarden.

**How reliable is the auto-fill in general?:**
I've never encountered any issues with the auto-fill feature in Bitwarden on Chromium based browsers however on Firefox Bitwarden will sometimes not fill the first time however will on the second.

**Where there any instances where the auto-fill did not work as expected / intended?:**
When using Firefox, issue stated in the question above.

**Anything specific you really liked?:**
The browser extension is as fully fledged as the desktop and mobile clients. Meaning you can do anything on the browser extension that you'd be able to do on the desktop client.

**Anything specific that bothered you?:**
A very big yes here. Bitwarden doesn't work in private mode on Firefox. It's been like this for years. You're able to auto-fill however only using the context menu options and you have to already be logged in which means switching to a non-private window to login then switching back to the private window to auto-fill. You also have to do this back and forth with anything whilst in private mode because the Bitwarden UI is completely disabled in private mode. This is the only reason I'm looking for an alternative to Bitwarden, other that this issue it's the perfect password manager.

**Did you encounter any performance issues?:**
No.

**What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10):**

- **Auto-fill:** 10
- **Add, remove and edit entries:** 10
- **TOTP auto-fill or auto-copy:** 10
- **Support for Chromium based browsers and Firefox:** 10
- **To work fully in Firefox private mode:** 10
- **To eventually have all of the features the desktop client has:** 5

**Do you have any specific security-related concerns?:**
Not really, I'm not a developer, I just assume it'll be made to be secure.

**Rate the following aspects in terms of priority (1 - 10):**

- **Convenience:** 10
- **Security:** 10
- **Performance:** 7

**Anything else you'd like to add?:**
I'm a power-user with high expectations. What I expect is probably not going to be what the general user expects.

**Comment by MaKleSoft** [comment]
Ok, so we have a first draft available for testing!

The prebuilt archive can be found here: https://github.com/padloc/padloc/releases/download/v3.0.13/padloc-extension-v2.0.13.zip
If you want to build the extension yourself (optionally pointing at your own backend):

```sh
cd packages/extension
PL_SERVER_URL=[custom_server_url] npm run build
```

A couple of notes:

- Tested in Chrome and Firefox but possibly also works in other browsers that support the browser extension standard. Feel free to test in other browsers and report your findings!
- This "extension" is really a fully functional version of the app. You can do anything in it that you can do in the web interface or any of the native apps, including creating and editing vault items!
- For now we've decided to keep the level of automation to a minimum, requiring explicit user interaction for things like filling forms and saving credentials. We believe that this is preferable to automagically guessing filling formulas and intercepting form submissions, as this would require a level of guesswork and intrusive dom manipulation that we would like to avoid. 
- Content scripts are designed work as unintrusively as possible and are only injected upon explicit user action.
- Fields can be filled in the following ways:
    - Drag and drop directly from the extension popup
    - Via the context menu by right-clicking on a form field
    - While a form field has focus, open the popup and click on the corresponding field
- As you would expect, vault items are matched automatically with the url of the current tab via fields of type `url`. Multiple `url` fields can be added to an item to match agains multiple domains.
- Shortcut for opening the extension popup: Cmd/Ctrl + Shift + P

Please try it out and let us know what you think!

**Comment by mzch** [comment]
Good extension! :)
But could you add a setting of api server? Now it seems to hardcode `api.padloc.app`...

**Comment by MaKleSoft** [comment]
@mzch if you can't to use a custom server you'll have to build from source as described my previous comment.

**Comment by mzch** [comment]
@MaKleSoft Oh, of course, I can build extension from source but if able to set a server URL in extension popup, I think more usable. :)

**Comment by MaKleSoft** [comment]
For those who haven't seen it yet: We've officially released our browser extension for Chrome and Firefox: https://padloc.app/blog/browser-extension-released/

Closing this issue now. Feel free to continue writing feedback here or if you have any specific feature requests / bug reports create a new issue!

**Comment by rugk** [comment]
1.
a) KeePassXC-Browser / Passman (Nextcloud) / Firefox built-in
b) In the latest KeePassXC-Browser version it is quite realiable.
c) mostly: single-username logins/logins where the password field appears later; password-only logins sometimes too
d) KeePassXC-Browser has many ways to manually trigger the autodetection (context menu). This is nice as it allows to workaround the edge-cases/problems. It also can configure "username-only" detection in the settings for specific sites.
I also like that I have to/can restrict which entries are transferred to the 
e) It broke from time to time in KeePassXC, motsly due to communication between the browser & desktop app though.
f) no, not really, only realibility issues
2. (ideas mostly stolen from otzher cvomments here, just adding my rating)
autofill – 10
auto-save – 8
search inside add-on – 3
own instance/choose instance – 10
Firefox support – 8
Chrome/ium support – 5
Other browser suppotrt – 2
Multiple accounts per site – 8
TOTP support – 5

----


uups, just now saw I'm late to the party, sorry. Did not test you extension/system yet.

**Comment by RyanZeho** [comment]
2023 Edition
a) Lastpass
b) Good, only a low amount of websites where it failed
c) Mainly websites in which the login was changed, or Input types were weirdly out of order 
d) Autofill on navigating to the website & passwordless logins for teams.
e) -
f) No
What features would you like the Padloc extension to have? (assign a priority rating between 1 and 10)
Do you have any specific security-related concerns?
Rate the following aspects in terms of priority (1 - 10)
- Autofill | 10
- Auto-Save | 8
- Search and Multiple selections at the same time | 8
Anything else you'd like to add?
I'm really trying to love padloc for all its simplicity, ease and nice UI design, the only thing really taking out the air for me as an entrepreneur is the fact that I need to drop or paste in the passwords and save them manually.
