### ISSUE TITLE
Certain characters in field values break csv export

### ISSUE THREAD

**Issue by chaosbunker** [padloc/padloc#266]
I noticed that when exporting the database to csv in the Desktop app, no file is actually saved. 

When exporting in Firefox the base64 string is shown in the address bar. I manually decoded it and noticed that there was a lot of garbage data (besides partly correctly decoded data). In many instances the garbage started where a `>` should have been.

Most (if not all) fields that break csv export had been imported from padlock 2.

Export to encrypted file works fine, so I isolated one entry and exported it for you to look at. I couldn't attach it here, so I'll email it to you.

**Comment by MaKleSoft** [comment]
Turns out the problem was that we were using URL-save encoding to generate the data url for the download link instead of regular base64 encoding. So the problem was not with specific characters but instead with the length of the exported data. I'm actually surprised this didn't surface earlier. @chaosbunker Thanks for bringing this to our attention!
