### ISSUE TITLE
[Feature Request] Endpoint for Health Check using GET Method by LoadBalancer

### ISSUE THREAD

**Issue by beah-s1** [padloc/padloc#279]
I was tried to build padloc on Google Kubernetes Engine using Google Cloud Load Balancer(GCLB)
But, GKE Ingress has require passing health check using GET method.

padloc is returning 405(method not allowed) error except for CONNECT/POST method.
So, It will be didn't work well.

I want you add health check endpoint using GET method.

**Comment by MaKleSoft** [comment]
Hm, interesting... Do you mind describing you use case a little more? Why would you want to put Padloc behind a load balancer?

**Comment by beah-s1** [comment]
When setup using GKE, I'll not have necessary mind status of infrastructure (e.g. VM) because if padloc is crashed, it will be restart automatically.
and, GCLB can signing and setup SSL certificate automatically after verify domain record.

**Comment by darkpixel** [comment]
A lot of apps use a URL of ```/healthcheck```.
A basic healthcheck would simply be that the app is up and able to serve a 200 response.
An advanced healthcheck might accept the HTTP GET request and do a check to see if the database accessible.

I can easily healthcheck the server because it returns a 200 response when it finishes starting up.
The API server doesn't appear to have an endpoint that returns anything other than 405 for unauthenticated GETs.

This make it difficult for kubernetes to handle failover and upgrades.  i.e. if you have two instances of the API server running and it needs to move them off to other servers to upgrade nodes, it has no idea if one or more of them are still starting up, have crashed, or are actually serving requests yet.

**Comment by BrunoBernardino** [comment]
Sorry I had missed this request. This isn't hard to implement and is necessary with something like k8s indeed. The URL is generally configurable and I've seen `/ping` used a lot, but I will implement `/healthcheck`.

**Comment by MaKleSoft** [comment]
I think making it configurable is a good idea. Let's add an option to [ServerConfig](https://github.com/padloc/padloc/blob/main/packages/core/src/server.ts#L67) and default to `/health` or whatever Kubernetes uses as a default path (if there is one).
