### ISSUE TITLE
Item not syncing from one device to other devices

### ISSUE THREAD

**Issue by chaosbunker** [padloc/padloc#291]
Hi Martin,

I have an item in a shared vault that I have updated 8 days ago on a iPad. On that device i renamed four PIN entries and added 5 more PIN entries, as well as one password type entry.

I wanted to access this item on my iPhone, but noticed that the item in question was outdated. All my recent changes were missing. I checked my laptop and the item was also outdated. Since I had passwords disappear before, I took my iPad offline, hoping the entries would still be there and I wouldn't lose them on that device from a sync or so. Fortunately they are there, I noted them down, went online to sync and then synced phone and laptop, but the item does not get updated.

Now .. to make things super weird. I checked this item again on my phone and it suddenly showed up with all entries and showed 'Last updated 8 days ago' at the bottom, which is correct. Moments later (after lock-screen of the phone) it changed back to the old version. Of course I doubted I had every seen the updated version of the item on the phone and wished I had a screenshot.. but then i repeated a couple time and it suddenly showed the updated version again (again the phone was in lock screen in-between) and after closing the item and going into lock screen and checking again, it was the 2 month old version again 🤷‍♂️ 

I'm maintaining my vault from four different devices and now wonder if this happens with other items 😒 It might explain some instances in the past where I was 100% sure I added an entry on a device and then it seemed like it disappeared

edit: all apps are up-to-date

**Comment by MaKleSoft** [comment]
Thanks for the detailed report! After getting some similar reports over the last couple of weeks I finally managed to reproduce the issue today and have (hopefully) found the cause. Basically what happened is that the mechanism used to flag locally changed vault items failed to properly mark items as "up-to-date" after pushing the local changes to the server, which under certain conditions resulted in a state where all the different devices constantly try to re-upload their local version of the item without ever reaching a "consensus". This is now fixed in master and a patch will go out soon.
