### ISSUE TITLE
Self-hosted: delete/remove account

### ISSUE THREAD

**Issue by detobel36** [padloc/padloc#313]
Is there a way to "manage" user and delete/remove an account from the database ?

**Comment by MaKleSoft** [comment]
At this point there is no "official" management tool available, no. There is a [REPL interface](https://github.com/padloc/padloc/blob/master/packages/server/src/repl.ts) that we're using internally but there is no official documentation for it yet and I'm hesitant to recommend it since it is no longer being actively developed and will likely be replaced by a more convenient management interface very soon (stay tuned 😉). I think the easiest way currently is to simply use one of the many LevelDB CLIs or GUIs available and delete the relevant entries from the database directly. I know this is not optimal but like I said, we'll have something for that soon 😊
