### ISSUE TITLE
Improve hostname matching for showing suggested items

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#397]
Imagine I have an item with the URL of `https://google.com`, for a Google account. When I try to sign in, that suggestion doesn't show, because the URL for logging in (right now) is `https://accounts.google.com`. While it's possible for me to change the URL in the item to match the new subdomain, it's not impossible for Google to eventually change that (to `https://auth.google.com`, for example), and then my items will stop showing as suggested.

While we have a matching logic for `www.{domain}`, we should also consider `*.{domain}`. This is especially bad for Apple accounts, because they frequently change the URL for the authentication form.

@MaKleSoft let me know if this is too complicated or impossible for v4 (not necessarily 4.0.0).

**Comment by MaKleSoft** [comment]
I'm torn on this... I agree that in many cases, this behaviour would be useful. But in general, it not guaranteed that whatever is hosted on a subdomain is in any way related (or even controlled by the same entity!) as what lives on the parent domain, and assuming so might be dangerous. A good example for this is Github pages: Let's say we're hosting an app at `https://my-app.github.io`. Now if someone stores an item for that app and isn't careful to include the subdomain in the url, Padloc will suggest that entry **for every single Github pages domain**! Now it's trivially easy for someone else to grab a GH-Pages subdomain that is very similar to my domain, put a phishing site on it, and hope that some people will simply mistype the url, e.g.: `https://my-ap.github.io`. Padloc will suggest the item that I've stored for `https://my-app.github.io` and before you know it, the user will have happily filled in their credentials thinking they're on the correct site. This may be a bit of a contrived example, but you see where I'm going with this.

The `www.` subdomain is a special case, since for most people, `www.example.com` is equivalent to `example.com` even though of course it isn't. This causes problems for sites that redirect the `www.` subdomain to the naked domain (like github does for example) or the other way around. So it's just easier to treat the two as equivalent.

In general though, I think it's safest to not make any assumptions about the relationship of subdomains and their parent domains. If you want an item to be suggested for multiple subdomains of the same site, you can always add multiple url fields to an item explicitly. E.g.:
- google.com
- accounts.google.com
- mai.google.com
- etc.

Another solution would be to allow wildcards in domain names, like `*.google.com`, but that would be hard to implement securely. Remember we can't store the host names in plain text, so we'd have to use some form of tokenisation to know which part of the host name is variable. In my opinion it's simply not worth it, since I doubt anybody other than power users would make use of it or even know the option exists.

**Comment by BrunoBernardino** [comment]
I actually prefer the `*.{domain}` idea as an alternative secure approach (and keep the default of not assuming the subdomains are safe). What would be the main difference between implementing that and the option of considering any subdomain of the domain safe?

**Comment by MaKleSoft** [comment]
You can see the index storage and matching mechanism here: https://github.com/padloc/padloc/blob/v4/packages/core/src/app.ts#L66

The problem is that host names are being hashed before they are stored, so we can't pattern-match on the index entries. I guess for the simple `*.{domain}` case, we could strip the `*.` part and add a flag like `matchSubdomains: true`. Then when matching a given host name, we could keep trying to strip domain parts until we get a match. For example:

We're on `login.accounts.google.com`. By default, Padloc will create the hash for that exact hostname (plus the `www.` variant) and compare that to all entries in the index. So only urls with that exact hostname will match. Now let's say we've added a url field `*.google.com`. Padloc could then store the hash of `google.com`, along with the `matchSubdomains: true` flag. If we encounter an entry with that flag, instead of just trying the exact match we would try all variants. I.e. `login.accounts.google.com`, `accounts.google.com` and `google.com`. If any of those match, we have have a winner.

**Comment by MaKleSoft** [comment]
Actually, maybe we don't need the flag. If we just store the hashed value of `*.google.com`, then we could simply try to find a match for the exact host name `login.accounts.google.com`, as well as `*.accounts.google.com` and `*.google.com`. Obviously this would have an impact on performance since we'd have to do this for every entry in the index, but I'd be surprised if the difference were big enough to really be noticeable (plus we're already doing this for the `www.` variant anyway).

**Comment by MaKleSoft** [comment]
So basically it would only be about adding a couple of lines to [`Index::fuzzyMatch`](https://github.com/padloc/padloc/blob/v4/packages/core/src/app.ts#L114). Yep, I'm warming up to the idea 😊.

**Comment by BrunoBernardino** [comment]
Thanks again for the links and detailed information. I think the performance impact wouldn't be noticeable (except maybe on older mobile clients and if that becomes a problem, we could add a setting to disable it), and the UX improvement would be nice.
