### ISSUE TITLE
Better error message when a vault is not yet accessible

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#514]
When giving an org member access to a new vault, they can't actually access it until someone else with previous access to that vault opens Padloc and reencrypts with their private key. Currently the error message says "you don't have access anymore" which is misleading in the case described above. We should be able to distinguish between cases where access was just given or access has been removed (by comparing the list of accessors with the access mapping in the org itself) and give an error message more appropriate to the situation.

<img width="463" alt="Screenshot 2022-07-29 at 08 42 28" src="https://user-images.githubusercontent.com/1270940/181699117-f8512a75-dabd-4663-8574-971486e5861b.png">

**Comment by BrunoBernardino** [comment]
@MaKleSoft I can't replicate this scenario. The moment I give someone access, the vault appears to be re-encrypted. How would this manifest in the code? Would it be the missing `encryptedKey` here: https://github.com/padloc/padloc/blob/1e5d133ee6f2e33d7842eeac1adf82c2bc38141c/packages/core/src/container.ts#L179 ?

**Comment by MaKleSoft** [comment]
It happens when you give yourself access to a vault, or in general when someone gives someone access to a vault they don't have access to themselves. This is because the user who has been assigned access has to wait until someone else with access to the vault opens it and re-encrypts it with the new accessor included.

**Comment by MaKleSoft** [comment]
Btw, how are you embedding the code reference for it to show up like this?

**Comment by BrunoBernardino** [comment]
Even when I remove myself, sync, and add myself again, I can never see the vault without having access to it, so that error never shows up.

I'm not sure how to do "when someone gives someone access to a vault they don't have access to themselves" though, excluding the scenario just above (with the own user).

For the embedding code you just need to go to a commit in GitHub and browse a file, and copy the link to a given line. Works for multiple lines too. It won't work matched to a branch because branches move, but commits don't.

If my question above doesn't fix it, I'm not sure how to tackle this, as I can't reproduce it.

**Comment by MaKleSoft** [comment]
> Even when I remove myself, sync, and add myself again, I can never see the vault without having access to it, so that error never shows up.

Hm, interesting. Let me try to reproduce this again myself. I'll take over from here.

**Comment by MaKleSoft** [comment]
Ok, here is how I reproduced the problem:

1. Create Vault and give access to some else, but not yourself
2. Add an item to the vault using the other user and synchronize
4. Give access to youself
