### ISSUE TITLE
[Android] Unable to specify self-hosted server on initial launch

### ISSUE THREAD

**Issue by scottmando2000** [padloc/padloc#573]
As the title specifies, when I initially launched the Android app, I was unable to specify a self-hosted server.
The only option as soon as it was started was an input for an email address.

**Comment by BrunoBernardino** [comment]
Hi @scottmando2000 ! The Android version is meant to be used with the SaaS offering at https://padloc.app. If you want to use it with a self-hosted version, you should build the app for it yourself.

You can see how we build it (signed) at https://github.com/padloc/padloc/blob/main/.github/workflows/build-cordova.yml#L64 so to build an unsigned version for yourself, you should be able to run:

```
PL_SERVER_URL=https://example.com/server/ npm run cordova:build:android
```

Assuming you've got the required dependencies installed, mentioned in https://github.com/padloc/padloc/tree/main/packages/cordova#requirements-android

Let me know if you need any further help!

**Comment by darkpixel** [comment]
It's a *huge* pain to set up the build infrastructure to accommodate Android and iPhone plus Chrome and Edge.  There are tons of hoops to jump through both technically and in Google, Apple, and Microsoft's appstore/playstore/extension store ecosystems.

It would be about 100,000 times easier if there was a small button at the bottom of the app that said "custom server"....or if a user could open a browser on their android/iphone and go to https://padloc.customdomain.tld to sign in and there was a button with a urlscheme that launched the padloc app and pointed it to the custom server automatically.

**Comment by BrunoBernardino** [comment]
Thanks for sharing your concerns @scottmando2000. You're correct that the process could be easier. That's why we prefer to work on simplifying the process of building the app yourself.

I'll still CC @MaKleSoft in case he thinks differently.

**Comment by dillfrescott** [comment]
Whenever an open source project has a paid option, and it's exceptionally difficult or an inconvenience to be able to self host it. I assume that the creators do this on purpose to try to get you to just give up and pay them money.

I'm not against the creators making money from a freemium product, I just think it should be easier to run yourself, if desired.

**Comment by darkpixel** [comment]
I think that's the root issue.
I have no problems donating money to an open source project that's useful.
I don't see a donate option.  Just an option to sign up and have them host my data for a monthly fee.
I don't want them hosting my data, for security reasons, so I don't need an account.
...but without an account, the chrome plugin is useless....so I'm not interested in donating at this time.

**Comment by BrunoBernardino** [comment]
You should be able to build an Android app without any problems. If you're talking about wanting a ready-to-install app where you can specify a custom server, you can see our answer at https://github.com/padloc/padloc/discussions/442

**Comment by darkpixel** [comment]
I would *love* to know the "security reasons" on why it would be apparently very, very bad to allow pointing to custom domains.  I use a handful of open source apps that all allow connecting to self-hosted instances and none of them are hand-waiving about "security reasons".

**Comment by c4lliope** [comment]
Hello all; I'm sorry to be the one to make this recommendation, though I can claim no patience for a program which disregards the needs of their users as though they're meaningless. Anyone seeing this kind of issue (basically, all besides the paying customers) should begin using https://www.passbolt.com/ - their apps and browser addons ask for the custom URL on the first screen, and since July 2022 I've been using them with no issue - simly make sure you keep a copy of the GPG key you're assigned on signup so you can log in from other machines.

I had high hopes for Padloc upon seeing such slick design and clear security audits displayed in their branding. I had even been able to deploy the program on my homelab's Dokku alongside all my homemade code. After a couple days of hacking on the deployment I'd been sure I had a good solution. Then as soon as I reached for the browser extension and android apps I realized I had a serious problem.

11 months ago, @MaKleSoft had said:

> Hi there! For security reasons, we do not currently support pointing the official apps to a custom server. However, are working on improving the tooling and documentation around building your own custom version of all apps and extensions! Additionally, we are considering releasing a "community edition" of all apps, which can be configured to be used with a custom server.

The "security" reason here is a red herring - custom domains are likely more secure than a single high-profile corporate domain handling all accounts. Padloc's programmers are saying, "you can run this yourself - if you can manage as large a presence on the app and browser stores as we do." This precludes any usage by the open-source coders who would likely help to make upgrades to the codebase after using it for personal or company use.

Padloc is disregarding user needs because they're picky regarding who their users are.
I'll be going back to https://www.passbolt.com/ and I recommend the same for many of you.
